from ..utils.exceptions import ExecuteError

class Executor:
    pass

