class ExecuteError(Exception):
    """
    Handle all Exceptions, that were caused in manage.py command;
    """
    pass
