class ExecuteError(Exception):
    """
    Handle all Exeptions, that were caused in manage.py command;
    """
    pass

